"""add make model year hierarchy fks

Revision ID: eaa9cd91bf7a
Revises: 4810f0cfe801
Create Date: 2026-07-15 10:48:28.936094

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'eaa9cd91bf7a'
down_revision: Union[str, None] = '4810f0cfe801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_models', sa.Column('make_id', sa.Integer(), nullable=False))
    op.drop_index('name', table_name='car_models')
    op.create_unique_constraint('uq_model_make_name', 'car_models', ['make_id', 'name'])
    op.create_foreign_key('fk_car_models_make_id_car_makes', 'car_models', 'car_makes', ['make_id'], ['id'])
    op.add_column('car_years', sa.Column('model_id', sa.Integer(), nullable=False))
    op.drop_index('year', table_name='car_years')
    op.create_unique_constraint('uq_year_model_year', 'car_years', ['model_id', 'year'])
    op.create_foreign_key('fk_car_years_model_id_car_models', 'car_years', 'car_models', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_car_years_model_id_car_models', 'car_years', type_='foreignkey')
    op.drop_constraint('uq_year_model_year', 'car_years', type_='unique')
    op.create_index('year', 'car_years', ['year'], unique=True)
    op.drop_column('car_years', 'model_id')
    op.drop_constraint('fk_car_models_make_id_car_makes', 'car_models', type_='foreignkey')
    op.drop_constraint('uq_model_make_name', 'car_models', type_='unique')
    op.create_index('name', 'car_models', ['name'], unique=True)
    op.drop_column('car_models', 'make_id')
    # ### end Alembic commands ###
    